# Build configuration file for deploying on Netlify
# Support for multi-environment builds, as needed
# "base" is the directory where the build script is run from
# "publish" is the directory to publish
# "command" is the build command

[build]
    base    = ""
    publish = "public/"
    command = "GATSBY_ACTIVE_ENV=dev npm run build"

# Production context: New commits to the main
# repo will be deployed with these settings
[context.production]
    command = "GATSBY_ACTIVE_ENV=prod npm run build"

# Deploy Preview context: Allow deploy previews
[context.deploy-preview]
    command = "GATSBY_ACTIVE_ENV=dev npm run build"

# Branch Deploy context: Commits pushed to other branches.
[context.branch-deploy]
    command = "GATSBY_ACTIVE_ENV=dev npm run build"